### PR TITLE
add : Duplicate Rules Checker

### PR DESCRIPTION
**Pull request by CYBERDEVILZ**
Runs on PR. If the rules match exactly, then an error is generated.

Fix for this issue

### CODE REVIEW

**Comment by krnick** [comment]
Hi @CYBERDEVILZ , thanks for helping create this duplicate rules checker.

I tried it and found that when there are three or more same files, only two of the duplicate files are displayed.

Reproduce it:
```
cp 00001.json 00200.json
cp 00001.json 00201.json
```

```
python3 .github/workflows/duplicate-checks.py
>>> found duplicates - ['00001.json', '00201.json']
```

Furthermore, by using hashing such as MD5, you could find these duplicated files fast.

**Comment by CYBERDEVILZ** [comment]
Hi @krnick 
In the above scenario, you have created two copies of 00001.json ( i.e. 00200.json and 00201.json ). Hence it will show any two of the three files. If you want me to show all the instances of duplicate files then I can create a program for that.

I gave a thought about hashing the file contents and comparing them. But the issue with this is, suppose there are some extra newlines in one file and the other file does not having any extra newlines then both the files will be considered different, even though they convey the same rules.

For example, consider these files:-

**File A**
```
{
    "crime": "Initialize bitmap object and compress data (e.g. JPEG) into bitmap object",
    "permission": [],
    "api": [
        {
            "class": "Landroid/graphics/BitmapFactory;",
            "method": "decodeByteArray",
            "descriptor": "([B I I)Landroid/graphics/Bitmap;"
        },
        {
            "class": "Landroid/graphics/Bitmap;",
            "method": "compress",
            "descriptor": "(Landroid/graphics/Bitmap$CompressFormat; I Ljava/io/OutputStream;)Z"
        }
    ],
    "score": 1,
    "label": [
        "camera"
    ]
}




```

**File B**
```
{
    "crime": "Initialize bitmap object and compress data (e.g. JPEG) into bitmap object",
    "permission": [],
    "api": [
        {
            "class": "Landroid/graphics/BitmapFactory;",
            "method": "decodeByteArray",
            "descriptor": "([B I I)Landroid/graphics/Bitmap;"
        },
        {
            "class": "Landroid/graphics/Bitmap;",
            "method": "compress",
            "descriptor": "(Landroid/graphics/Bitmap$CompressFormat; I Ljava/io/OutputStream;)Z"
        }
    ],
    "score": 1,
    "label": [
        "camera"
    ]
}
```

MD5 hash of FILE A - 27623c59cf0ceb68bae5eafb3514ca75
MD5 hash of FILE B - d5e34ace658f1ebdd3ca54aff760b1d0

Both are different.

Hence I decided to strip all the whitespaces and newlines and then compare them.

**Comment by krnick** [comment]
> Hi @krnick
> In the above scenario, you have created two copies of 00001.json ( i.e. 00200.json and 00201.json ). Hence it will show any two of the three files. If you want me to show all the instances of duplicate files then I can create a program for that.

I prefer to display all duplicate files since we can check which file is duplicated according to the number of the rules and decide to delete it.


> I gave a thought about hashing the file contents and comparing them. But the issue with this is, suppose there are some extra newlines in one file and the other file does not having any extra newlines then both the files will be considered different, even though they convey the same rules.
> 
> For example, consider these files:-
> 
> **File A**
> 
> ```
> {
>     "crime": "Initialize bitmap object and compress data (e.g. JPEG) into bitmap object",
>     "permission": [],
>     "api": [
>         {
>             "class": "Landroid/graphics/BitmapFactory;",
>             "method": "decodeByteArray",
>             "descriptor": "([B I I)Landroid/graphics/Bitmap;"
>         },
>         {
>             "class": "Landroid/graphics/Bitmap;",
>             "method": "compress",
>             "descriptor": "(Landroid/graphics/Bitmap$CompressFormat; I Ljava/io/OutputStream;)Z"
>         }
>     ],
>     "score": 1,
>     "label": [
>         "camera"
>     ]
> }
> ```
> 
> **File B**
> 
> ```
> {
>     "crime": "Initialize bitmap object and compress data (e.g. JPEG) into bitmap object",
>     "permission": [],
>     "api": [
>         {
>             "class": "Landroid/graphics/BitmapFactory;",
>             "method": "decodeByteArray",
>             "descriptor": "([B I I)Landroid/graphics/Bitmap;"
>         },
>         {
>             "class": "Landroid/graphics/Bitmap;",
>             "method": "compress",
>             "descriptor": "(Landroid/graphics/Bitmap$CompressFormat; I Ljava/io/OutputStream;)Z"
>         }
>     ],
>     "score": 1,
>     "label": [
>         "camera"
>     ]
> }
> ```
> 
> MD5 hash of FILE A - 27623c59cf0ceb68bae5eafb3514ca75
> MD5 hash of FILE B - d5e34ace658f1ebdd3ca54aff760b1d0
> 
> Both are different.
> 
> Hence I decided to strip all the whitespaces and newlines and then compare them.

That makes sense, thanks for clarifying it.

**Comment by CYBERDEVILZ** [comment]
I have made changes to the code. Please take a look at it.

**Review by krnick — APPROVED** [review]
Thanks @CYBERDEVILZ , it LGTM :D

**Pull request merged**
